BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
WS2812_DRIVER = vendor      # Let me try the PIO driver
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
ENCODER_ENABLE = yes        # Enables the use of one or more encoders
ENCODER_MAP_ENABLE = yes    # uint16_t encoder_map[NUM_LAYERS][NUM_ENCODERS][NUM_DIRECTIONS] in keymap.c
SERIAL_DRIVER = usart
TAP_DANCE_ENABLE = yes
